version: "3.8"
services:
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV={APP_ENV}
    environment:
      - APP_ENV={APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /home/deb/laravel-realworld-example-app/storage/logs:/var/www/logs
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis



  database:
    image: mysql:5.7.22
    ports:
      -  3306:3306
    environment:

      -  MYSQL_USER=${DB_USERNAME}
      -  MYSQL_PASSWORD=${DB_PASSWORD}
      -  MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      -  MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - /home/deb/laravel-realworld-example-app/storage/logs:/var/www/logs
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      -  6379:6379




volumes:
  db-data:
    driver: local
  logs: ~

